config/routes.rb
CarManager::Application.routes.draw do
  
  get 'users/settings'

  devise_for :users
  root to: 'pages#index'
  get 'pages/index'

  controller :users do
    get 'settings'
  end

  resources :cars do
    member do
      get 'more_records'
      get 'import'
      patch 'upload'
    end

    resources :gas_records, only: [:index, :new, :create, :destroy] do
      member do
        post 'toggle_stats'
      end
    end

    resources :service_records, only: [:index, :new, :create, :destroy]
  end
end

app/models/gas_record.rb
class GasRecord < Record

  after_save :update_mpg
  after_destroy :update_mpg

  alias_attribute :distance, :mileage

  def update_mpg
    car.update_mpg
  end

  def stat?
    stat
  end

  def to_s
    "#{date} #{distance} #{volume} #{cost}"
  end
end

app/controllers/gas_records_controller.rb
class GasRecordsController < ApplicationController

  def index
    @car = current_user.cars.find(params[:car_id]) || not_found

    respond_to do |format|
      format.csv do
        filename = "#{@car.name.tr(' ', '_')}_#{Date.today.strftime("%Y%m%d")}_gas.csv"
        send_data @car.to_csv(:gas), filename: filename
      end
    end
  end

  def new
  end

  def create
    @record = GasRecord.new(record_params)
    @record.date = @record.date.strftime('%Y-%m-%d')

    if @record.mileage.nil? || @record.volume.nil?
      # disable mileage stats for record
    end

    if @record.cost.nil?
      #disable price stats for record
    end

    if @record.date.nil?
      #disable time stats for record
    end

    if @record.save
      @records = @record.car.gas_records
      message 'success', "Record successfully created."
      redirect_to car_path(@record.car, :anchor => 'tab_gas')
    else
      render action: "new"
    end
  end

  def destroy
    @record = GasRecord.find(params[:id])
    car = @record.car
    if current_user.id == car.user_id
      @record.destroy
      message 'success', "Record deleted successfully."
      redirect_to car_path(car, :anchor => 'tab_gas')
    else
      message 'error', "You do not have permission to delete this record."
      redirect_to cars_url
    end
  end

  def toggle_stats
    @record = GasRecord.find(params[:id])
    if @record.stat?
      @record.update(stat: false)
    else
      @record.update(stat: true)
    end
    redirect_to car_path(@record.car, :anchor => 'tab_gas')
  end

  private
  def record_params
    params.require(:gas_record).permit(:car_id, :date, :mileage, :volume, :cost)
  end
end

app/views/gas_records/_gas_record.html.slim
tr class="#{'no-stat' unless gas_record.stat?}"
  td.date= gas_record.date.strftime('%b %-d, %Y')
  td.mileage= number_with_delimiter(gas_record.mileage.round, delimiter: ',')
  td.volume= number_with_precision(gas_record.volume, precision: 2)
  td.cost= number_to_currency(gas_record.cost)

  td.hidden-xs.text-right.actions
    = link_to toggle_stats_car_gas_record_path(gas_record.car, gas_record.id), method: :post, class: "btn btn-xs btn-default" do
      | stats
      span.glyphicon class="glyphicon-#{gas_record.stat? ? 'ok' : 'none'}"
    = link_to 'delete', [gas_record.car, gas_record], method: :delete, class: "btn btn-xs btn-danger", data: { confirm: "Are you sure you want to delete this record?" }

app/views/gas_records/_list.html.slim
table.table.records
  thead
    tr
      th Date
      th Mileage
      th= current_user.volume_unit
      th Cost
      th.hidden-xs
  tbody.gas-tbody
    = render records

app/views/gas_records/_new.html.haml
%h3 Add Gas
= form_for [@car, GasRecord.new], html: {class: 'form-horizontal', novalidate: true} do |f|
  = f.hidden_field :car_id, value: @car.id

  .form-group
    = f.label :date, class: 'control-label col-xs-3'
    .col-xs-9
      .input-group
        .input-group-btn
          .btn.btn-default.today Today
        = f.text_field :date, class: 'form-control date', autocomplete: 'off'

  .form-group
    = f.label :mileage, class: 'control-label col-xs-3'
    .col-xs-9
      .input-group
        = f.number_field :mileage, class: 'form-control', autocomplete: 'off'
        %span.input-group-addon= current_user.distance_unit.downcase

  .form-group
    = f.label :cost, class: 'control-label col-xs-3'
    .col-xs-9
      .input-group
        %span.input-group-addon $
        = f.number_field :cost, class: 'form-control', autocomplete: 'off'

  .form-group
    = f.label :volume, current_user.volume_unit, class: 'control-label col-xs-3'
    .col-xs-9
      .input-group
        = f.number_field :volume, class: 'form-control', autocomplete: 'off'
        %span.input-group-addon= current_user.volume_unit.downcase

  .text-right
    = f.submit 'add', class: 'btn btn-primary btn-lg'

app/views/gas_records/_new.html.slim
h3 Add Gas
= form_for [@car, GasRecord.new], html: {class: 'form-horizontal', novalidate: true} do |f|
  = f.hidden_field :car_id, value: @car.id

  .form-group
    = f.label :date, class: 'control-label col-xs-3'
    .col-xs-9
      .input-group
        .input-group-btn
          .btn.btn-default.today Today
        = f.text_field :date, class: 'form-control date', autocomplete: 'off'

  .form-group
    = f.label :mileage, class: 'control-label col-xs-3'
    .col-xs-9
      .input-group
        = f.number_field :mileage, class: 'form-control', autocomplete: 'off'
        span.input-group-addon= current_user.distance_unit.downcase

  .form-group
    = f.label :cost, class: 'control-label col-xs-3'
    .col-xs-9
      .input-group
        span.input-group-addon $
        = f.number_field :cost, class: 'form-control', autocomplete: 'off'

  .form-group
    = f.label :volume, current_user.volume_unit, class: 'control-label col-xs-3'
    .col-xs-9
      .input-group
        = f.number_field :volume, class: 'form-control', autocomplete: 'off'
        span.input-group-addon= current_user.volume_unit.downcase

  .text-right
    = f.submit 'add', class: 'btn btn-primary btn-lg'