config/routes.rb
CarManager::Application.routes.draw do
  
  get 'users/settings'

  devise_for :users
  root to: 'pages#index'
  get 'pages/index'

  controller :users do
    get 'settings'
  end

  resources :cars do
    member do
      get 'more_records'
      get 'import'
      patch 'upload'
    end

    resources :gas_records, only: [:index, :new, :create, :destroy] do
      member do
        post 'toggle_stats'
      end
    end

    resources :service_records, only: [:index, :new, :create, :destroy]
  end
end

app/views/shared/_favicons.html.slim
link href="/apple-touch-icon-57x57.png" rel="apple-touch-icon" sizes="57x57" /
link href="/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114" /
link href="/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72" /
link href="/apple-touch-icon-60x60.png" rel="apple-touch-icon" sizes="60x60" /
link href="/apple-touch-icon-120x120.png" rel="apple-touch-icon" sizes="120x120" /
link href="/apple-touch-icon-76x76.png" rel="apple-touch-icon" sizes="76x76" /
link href="/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png" /
link href="/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png" /
link href="/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png" /
meta content="#ffc40d" name="msapplication-TileColor" /

app/views/shared/_navigation.html.slim
nav.navbar.navbar-default(role='navigation')
  .container
    .navbar-header
      button.navbar-toggle(type='button' data-toggle='collapse' data-target='#navbar-collapse')
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      - if current_user
        - if current_user.primary_car
          = link_to "Car Manager", current_user.primary_car, class: 'navbar-brand', title: "View primary car"
        - else
          = link_to "Car Manager", cars_url, class: 'navbar-brand', title: "View cars"
      - else
        = link_to "Car Manager", root_url, class: 'navbar-brand', title: "Go to main page"
    ul.nav.navbar-nav.navbar-left.hidden-xs
      li
        p.navbar-text.nav-hint

    .collapse.navbar-collapse#navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if current_user
          li= link_to "Cars", cars_url
          li= link_to "Settings", settings_url
          li= link_to "Sign Out", destroy_user_session_url
        - else
          li= link_to "Sign In", new_user_session_url
          li= link_to "Register", new_user_registration_url